### ISSUE TITLE
can't create new weight file

### ISSUE THREAD

**Issue by Techlord210** [tusharhero/perceptron#5]
```
(py311_venv) E:\co\perceptron>py train.py -w newweight
Traceback (most recent call last):
  File "E:\co\perceptron\train.py", line 57, in <module>
    ag.train(enouchs=int(args.enouchs), weightpath=args.weight, no_visualize_weight=args.no_visualize_weight, verbose=args.verbose)
  File "E:\co\perceptron\algorithm.py", line 117, in train
    weight = eval(getfilecontent(weightpath))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\co\perceptron\algorithm.py", line 60, in getfilecontent
    with open(filepath, 'r') as fp:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'w'

(py311_venv) E:\co\perceptron>py train.py -w newweight
Traceback (most recent call last):
  File "E:\co\perceptron\train.py", line 57, in <module>
    ag.train(enouchs=int(args.enouchs), weightpath=args.weight, no_visualize_weight=args.no_visualize_weight, verbose=args.verbose)
  File "E:\co\perceptron\algorithm.py", line 117, in train
    weight = eval(getfilecontent(weightpath))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 0

SyntaxError: invalid syntax
```
if i create a new file with `[]` as its content:
```
(py311_venv) E:\co\perceptron>py train.py -w newweight
Traceback (most recent call last):
  File "E:\co\perceptron\train.py", line 57, in <module>
    ag.train(enouchs=int(args.enouchs), weightpath=args.weight, no_visualize_weight=args.no_visualize_weight, verbose=args.verbose)
  File "E:\co\perceptron\algorithm.py", line 157, in train
    product = multiply(weight, image_list)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\co\perceptron\algorithm.py", line 94, in multiply
    product += weight[i] * image_list[i]
               ~~~~~~^^^
IndexError: list index out of range

(py311_venv) E:\co\perceptron>
```

**Comment by Techlord210** [comment]
> You need to create the new weight with current size.

what do you mean *current size*

**Comment by tusharhero** [comment]
Well, its an argument in `train()`, you need to take a size argument in `getfilecontent()` and fill it with random values. To be honest, we should consider creating a separate functions to make this case, because the function is named `getfilecontent()` and that's the only thing it should **do**.

**Comment by Techlord210** [comment]
> Well, its an argument in `train()`, you need to take a size argument in `getfilecontent()` and fill it with random values. To be honest, we should consider creating a separate functions to make this case, because the function is named `getfilecontent()` and that's the only thing it should **do**.

How many values I have to fill it with and whats the range of random values

**Comment by tusharhero** [comment]
>>To be honest, we should consider creating a separate functions to make this case, because the function is named `getfilecontent()` and that's the only thing it should **do**.
> 
> How many values I have to fill it with and whats the range of random values

I think first of all you should divide this task into another function because `getfilecontent()` is supposed to get file content. 
> How many values I have to fill it with and whats the range of random values

The range of random values does not matter.

**Comment by Techlord210** [comment]
> Give me a PR

[0e4751c](https://github.com/tusharhero/perceptron/pull/6/commits/0e4751c8c0064290359879117813a308ef3d5f25)
